### PR TITLE
feat(core): respect pointers in overrides 

### LINKED ISSUE #1002: [RFC] Teach overrides to honor JSON Pointers
Potential laxer locations syntaxes have been evoked in #939 and eventually dropped out to keep the PR on scope.

This issue is a placeholder to gather feedback, use cases and try and measure how important allowing less strict locations would be.

From https://github.com/stoplightio/spectral/pull/939#discussion_r387493237

Current location syntax is: `<source>#<pointer>` where
 - `source` can be expressed as 
    - an absolute uri (file or http based)
    - relatively to the to the rulesepath uri
- `pointer` is a Json pointer (cf. https://tools.ietf.org/html/rfc6901) describing the precise document path that should be ignored

Latest update to the proposal was to allow a more open location syntax where 
- [x] `<source>` could be optional #1423 
- [x] `#<pointer>` could be optional #1405 
- [x] at least one of them should be described #1423 
- [ ]  `<pointer>` meaning would change

**Samples:**
- `models/awful.json: [ rule1, rule2]`: Would ignore rule1 and rule2 results wheverever in the file
- `#/info": [rule1, rule2]`: Would ignore rule1 and rule2 results in any processed document provided they originate from a path that's `#/info` **or below (eg. `#/info/sub/path/1`)**. This would be in line with @P0lip's [comment](https://github.com/stoplightio/spectral/pull/939#discussion_r371174774)

### PR DESCRIPTION
**Pull request by P0lip**
Closes #1002 

**Checklist**

- [x] Tests added / updated
- [ ] Docs added / updated

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by domagojk** [comment]
Hm do we have a type-check in cirlceCi? I have dozen of different errors, like:

Screen Shot 2021-07-01 at 14 03 33

Screen Shot 2021-07-01 at 14 05 13

also seems there is a failing test in `ci/circleci: test-node-current` 👀

**Comment by P0lip** [comment]
> Hm do we have a type-check in cirlceCi? I have dozen of different errors, like:

Have you run `lerna bootstrap?

**Comment by domagojk** [comment]
> Have you run `lerna bootstrap`?

Not at the time but I've tried now and I still get the errors. But when I run `yarn build` I got no errors, so it could be the problem is at my end

**Review by domagojk — APPROVED** [review]
yea it was typescript version 🤦 

LGTM 😄

**Pull request merged**
