### PR TITLE
fix #915: Ignore examples with circular schemas

### LINKED ISSUE #915: oas3-valid-(content-)schema-example: can't handle circular references
**Describe the bug**

It seems that in some cases the rules oas3-valid-schema-example and oas3-valid-content-schema-example fail although the examples and JSON paths are valid (afaik).

I get in the command line:
```
 2040:25  error  oas3-valid-content-schema-example  can't resolve reference #/components/schemas/process_json_schema from id #
 4745:15  error  oas3-valid-content-schema-example  can't resolve reference #/components/schemas/process_arguments from id #
 4745:15  error  oas3-valid-schema-example          can't resolve reference #/components/schemas/process_arguments from id #
 5016:29  error  oas3-valid-content-schema-example  can't resolve reference #/components/schemas/process_arguments from id #
```

**To Reproduce**

OpenAPI document: https://raw.githubusercontent.com/Open-EO/openeo-api/spectral/openapi.yaml

.spectral.yml
```
extends: "spectral:oas"
```

Run: `spectral lint openapi.yaml`

**Expected behavior**

No warnings/errors

**Environment (remove any that are not applicable):**
 - Library version: 5.0.0 and develop branch
 - OS: Windows 10

### PR DESCRIPTION
**Pull request by m-mohr**
Fixes #915.

**Checklist**

- [ ] Tests added / updated
- [ ] Docs added / updated

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

**Additional context**

This is a first very dump attempt at #915, see the issues for more context. This is more a workaround than a proper fix, but I don't see a better alternative that doesn't need a lot of work yet.

Better would be to send an information instead of an error when ignoring, but not sure how to do that. 

The rules could be changed as follows whenever users want to ignore examples with circular schemas:

```
"oas3-valid-schema-example": {
      "description": "Examples must be valid against their defined schema.",
      "message": "{{error}}",
      "severity": 0,
      "formats": ["oas3"],
      "recommended": true,
      "type": "validation",
      "given": "$.components.schemas..[?(@property !== 'properties' && @.example && (@.type || @.format || @.$ref))]",
      "then": {
        "function": "schemaPath",
        "functionOptions": {
          "field": "example",
          "schemaPath": "$",
          "oasVersion": 3,
          "ignoreCircular": true
        }
      }
    }
```

Even better would be to simply inherit by specifying just the additional rule, but I don't know how to achieve it.
```json
"oas3-valid-schema-example": {
  "ignoreCircular": true
}
```

### CODE REVIEW

**Comment by aerfus** [comment]
Hello,
@m-mohr do you plan to release the feature in the near future?

**Comment by m-mohr** [comment]
@aerfus It's not on me releasing this. You need to ask @P0lip and the others at stoplight.io.

To be honest, this only a hack to stop failures in the CI. I guess a better solution would be to use #939 or fix the bug completely so that recursive schemas can be validated.

**Comment by aerfus** [comment]
@m-mohr I see, thank you for the information!

**Comment by P0lip** [comment]
@m-mohr please accept my sincere apologies for dropping a ball here. It's been a couple of hectic days for me and didn't have much time to contribute to Spectral. :sad:

I'm more than happy to release a minor release once this is in, since there are a couple of others PRs we've already merged and it makes sense to get that stuff out to public.

@nulltoken mind giving a look at this PR?

**Comment by nulltoken** [comment]
@P0lip on it, Sir!

@m-mohr Few thoughts:
- Rather than short circuiting the function, I believe that your [proposal](https://github.com/stoplightio/spectral/issues/915#issuecomment-575586303) of letting the user know about this shortcoming may be of great value. Taking a look at [`typedEnums.ts`](https://github.com/stoplightio/spectral/blob/develop/src/functions/typedEnum.ts) might be a good start to see how we can return custom-made messages.
- My understanding of the current version of the code is that it doesn't only focus on circular references but would actually exclude any schema that includes a `$ref`. Would that be correct, it might be a bit too broad (as composing schemas is a widely used feature).
- With regards to detecting circular references, it's possible that the `DepGraph` feature _may_ (⚠️ Unvalidated blurry "gut feeling" area) be helpful
Spectral internally leverage the `dependency-graph` library. And it happens that detecting cycles seems to already be a thing (https://github.com/jriecken/dependency-graph/issues/25).  FWIW, you can find an example of the `graph` thingie usage in [`unreferencedReusableObject.ts`](https://github.com/stoplightio/spectral/blob/develop/src/functions/unreferencedReusableObject.ts)

Minor things that this PR would require in order to be merged:
- updating the related doco to describe the change in the `schemaPath` options
- some tests to demonstrate the feature (and protect it from potential regressions)

**Comment by m-mohr** [comment]
Thanks for the review @nulltoken. No need to apologize, @P0lip :-)

> * Rather than short circuiting the function, I believe that your [proposal](https://github.com/stoplightio/spectral/issues/915#issuecomment-575586303) of letting the user know about this shortcoming may be of great value. Taking a look at [`typedEnums.ts`](https://github.com/stoplightio/spectral/blob/develop/src/functions/typedEnum.ts) might be a good start to see how we can return custom-made messages.

The problem is that (at least in my case) I would still want the CI to fail if examples are not correct, but only for circular referenced examples that can't be validated properly I want to send an info. I can't see anything in typedEnums.ts that lets me set the severity though.

> * My understanding of the current version of the code is that it doesn't only focus on circular references but would actually exclude any schema that includes a `$ref`. Would that be correct, it might be a bit too broad (as composing schemas is a widely used feature).

As far as I understood the schemas are dereferenced and $ref are only left in place where it couldn't resolve the ref (usually when there's a circular ref). So that shouldn't be a problem, but I'm not deeply invested in your source code so that might be a wrong assumption (although it works in my tested cases).

> * With regards to detecting circular references, it's possible that the `DepGraph` feature _may_ (⚠️ Unvalidated blurry "gut feeling" area) be helpful
>   Spectral internally leverage the `dependency-graph` library. And it happens that detecting cycles seems to already be a thing ([jriecken/dependency-graph#25](https://github.com/jriecken/dependency-graph/issues/25)).  FWIW, you can find an example of the `graph` thingie usage in [`unreferencedReusableObject.ts`](https://github.com/stoplightio/spectral/blob/develop/src/functions/unreferencedReusableObject.ts)

That's a bit too deep into things I don't know enough about. I'm also a bit limited on time and can't dig into these details at the moment.

> Minor things that this PR would require in order to be merged:

I'm not even sure we need to merge it. As far as I understood PR #939, that PR could also solve the issue as I could just ignore the circular schemas with it?!

> * updating the related doco to describe the change in the `schemaPath` options

The current solution is a bit verbose as required copying rules. Has anyone an answer for the question I raised in the PR description? Beforehand it doesn't make much sense to write docs.

**Comment by nulltoken** [comment]
@m-mohr 

>As far as I understood PR #939, that PR could also solve the issue as I could just ignore the circular schemas with it?!

It wouldn't fix the underlying bug identified by #915. It should help ignore the findings, though.
However, please keep in mind #939 is still in its early stages. It may take some time before it's even ready for a formal review.

**Comment by m-mohr** [comment]
> It wouldn't fix the underlying bug identified by #915.

Indeed, but I don't see this being fixed anytime soon as it seems to need fundamental changes in spectral?! So maybe we need workarounds to help with getting the CIs running for now. At the moment, spectral is very much useless for us as I can't run it in CI due to this bug.

> However, please keep in mind #939 is still in its early stages. It may take some time before it's even ready for a formal review.

Didn't know that. I thought it's relatively close to being ready. The issue is I'm pretty busy at the moment and can't work on this PR until mid-March or so.

**Comment by philsturgeon** [comment]
@nulltoken do you think the change we discovered in https://github.com/APIDevTools/json-schema-ref-parser/pull/158 will help here?

**Comment by m-mohr** [comment]
I don't think so, but not really sure. How should switching from `auto` to `id` help?

**Comment by nulltoken** [comment]
>@nulltoken do you think the change we discovered in APIDevTools/json-schema-ref-parser#158 will help here?

@philsturgeon It's possible than trying to `$Refparser.bundle()` the schema before compiling the result through ajv _might_ solve the issue. However, off the top of my head, adding the bundling step in the schema may also require:
 - to teach the rule engine to work with async functions  as `$Refparser.bundle` is async. @P0lip started a WIP in https://github.com/stoplightio/spectral/tree/feat/async-fns but it's possible we'd have to adapt/extend our tests to cover this
- to cover the execution of the `oas2` and `oas3` schema rules in offline context (in order to ensure calling `bundle()` against the generated static assets doesn't trigger any http call). I've got something in #974 that does this for asyncapi (cf. https://github.com/stoplightio/spectral/blob/36379eed50c4d47f5c016a81607b166f75a45df4/src/rulesets/asyncapi/__tests__/streetlights.jest.test.ts#L41-L61)

> I don't think so, but not really sure. How should switching from `auto` to `id` help?

@m-mohr I haven't studied the `id` vs `$id` thingie. Would this need to change in `oas2`, `oas3`, `any-other-context`, maybe allowing the rule writer to specify this option through a parameter to the schema function may help.

⚠️ Full disclosure, I haven't tested this extensively and I am far from being an AJV guru 😉

**Comment by P0lip** [comment]
Hey folks.
Is this still relevant?

**Comment by m-mohr** [comment]
I guess it's obsolete with the "except"ions from @nulltoken. So I'm closing the PR. Issue #915 is not solved though as the "except"ions are basically just a workaround around a spectral bug/limitation.

**Comment by nulltoken** [comment]
@P0lip With #939 and #1020 (which showcases how to work around specific circular schemas issues) in, I believe this is no longer relevant.

@m-mohr Thoughts?

**Comment by philsturgeon** [comment]
Seeing as we have a workaround for now, the long term solution will be handled by switching from stoplight/json-ref-resolver to APIDevTools/json-schema-ref-parser (https://github.com/stoplightio/spectral/issues/1054). 

Our ref resolver handles many circular reference scenarios, but this one has better support out of the box. If there is still a problem after we switch then it'll need to be fixed over there.

**Pull request closed without merging**
