### PR TITLE
perf(core): bump jsonpath-plus to 7.1.0

### PR DESCRIPTION
**Pull request by FredericKayser**
jsonpath-plus from 6.0.1 to 7.1.0

**Checklist**

- [X] Tests added / updated
- [X] Docs added / updated

**Does this PR introduce a breaking change?**

- [X] No

**Additional context**

Updated version of jsonpath-plus to improves performance significantly when a Swagger has many definitions. I reached up to 4x faster speeds with the update.

### CODE REVIEW

**Comment by FredericKayser** [comment]
@P0lip is it possible to adjust the required tests? (In case you want to sunset Node 12 support, but I don't know the benefit of supporting a deprecated version)

**Comment by P0lip** [comment]
> In case you want to sunset Node 12 support,

I'm afraid we cannot just sunset Node 12 support. We'd need a major release for that.
I believe you should be just fine updating `jsonpath-plus` to `7.0.1` without the nimma bump.
`yarn` will probably issue a warning, but I'm ok with it.

**Comment by FredericKayser** [comment]
Okay, thanks for your response. I will change it in the evening. :)

**Comment by FredericKayser** [comment]
@P0lip reverted nimma to 0.2.2 and NodeJS 12 and it works without warning

**Comment by P0lip** [comment]
Awesome. Could you please run `yarn dedupe` and commit yarn.lock?

**Comment by FredericKayser** [comment]
> Awesome. Could you please run `yarn dedupe` and commit yarn.lock?

done

**Review by P0lip — APPROVED** [review]
Thanks!

**Pull request merged**
