### PR TITLE
chore: minor JSONSchema typings tweak

### PR DESCRIPTION
**Pull request by P0lip**

### CODE REVIEW

**Comment by P0lip** [comment]
I noticed `Check Markdown Links / markdown-link-check (pull_request) ` task fails pretty often.

**Comment by philsturgeon** [comment]
That means there are broken links that we should fix!

**Comment by XVincentX** [comment]
@P0lip Me too, and the error it is returning is kind of weird; I'll give it another week otherwise I'll probably remove it from Prism since it's slowing me down unfortunately :(

**Comment by philsturgeon** [comment]
Great change 💯

**Pull request merged**
