### PR TITLE
chore: enlist Azure DevOps in the PullRequest checks

### PR DESCRIPTION
**Pull request by nulltoken**
cf. https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#pr-triggers

**Checklist**

- [ ] Tests added / updated
- [ ] Docs added / updated

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

While working on #635, I noticed that only CircleCi checks were triggered. 

image

However, PRs issued by core contributors were triggering AzureDevOps builds.

This PR is an attempt to get a Windows based CI build feedback when the PR originates from a fork of the repository and targets either `master` or `develop`.

### CODE REVIEW

**Comment by nulltoken** [comment]
As stated by the doc ("When the changes from the topic branch are merged into master, then the trigger will be fully configured."), this will start to be effective when this PR is merged.

@P0lip @XVincentX Thoughts?

**Comment by nulltoken** [comment]
@P0lip Is there any chance you could enlist this change in #631 so that it eventually reaches `master`? My understanding of the doc is that it's a prerequisite from the checks to eventually trigger.

**Comment by nulltoken** [comment]
> @P0lip Is there any chance you could enlist this change in #631 so that it eventually reaches `master`? My understanding of the doc is that it's a prerequisite from the checks to eventually trigger.

Another option would be for me to cherry pick pick this commit and open a new PR directly targeting `master` (which may help get this change landed sooner).

Thought?

**Comment by P0lip** [comment]
@nulltoken 
Ah, forgot to inform you I've already cherry-picked it.
It's already on master https://github.com/stoplightio/spectral/commits/master

**Comment by nulltoken** [comment]
@P0lip Thanks!

Unfortunately, it looks like something is still blocking #635 from running Windows based build (and somehow, that makes my xplat OCD cry a little...).

The [latest](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#pr-triggers) I've found on the topic seems to hint at a AzureDevOps UI configuration that may prevent building PRs from forks.

Moreover, the picture below (from this [post](https://dzone.com/articles/build-pipeline-triggers-using-azure-devopscicd)) seems to confirm that.
image

Any chance that someone with enough privileges could take a look at the server side conf of https://dev.azure.com/vncz/vncz/_build?definitionId=4 ?

**Comment by P0lip** [comment]
@XVincentX since you own that, could you take a look at your leisure?

@nulltoken don't worry about that for now. :) You are not touching anything OS-specific, so AzurePipeline checks are not that crucial on this particular occasion.

**Comment by nulltoken** [comment]
>You are not touching anything OS-specific, so AzurePipeline checks are not that crucial on this particular occasion.

@P0lip I know ;-) But you know, that thing... xplat OCD...  it's something that's very hard to get rid of :stuck_out_tongue_winking_eye:

**Pull request merged**
