### PR TITLE
fix: ruleset path for Example Object validation

### PR DESCRIPTION
**Pull request by johlo**
The `example` field has `Any` values in all contexts
it can be used so the rule should not be triggered for that field.

The `examples` field always has values of `Example Object` type in
all contexts, so this is what the rule should trigger on.
And since the `examples` field takes a map of example objects
the JSON path expression needs the final `.*` to work.

Updated the tests to validate `examples` field instead of `example` and added
one test.

**Checklist**

- [x] Tests added / updated
- [ ] Docs added / updated

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by nulltoken** [comment]
@johlo Looks pretty cool, thanks!

Next to the newly added test `validate multiple valid examples`, would you mind adding some additional ones to cover the following use cases?
- multiple examples with one of them exposing both `value` and `externalValue`
- multiple examples with one of them exposing neither `value` nor `externalValue`

**Comment by johlo** [comment]
>     * multiple examples with one of them exposing both `value` and `externalValue`
> 
>     * multiple examples with one of them exposing neither `value` nor `externalValue`

Done, amended to the old commit.

**Comment by johlo** [comment]
btw, when preparing this PR I've only run the `yarn test.prod` tests, I couldn't run `yarn test.harness` since `yarn build.binary` fails to build the binary (because I'm using node 13.5?).

**Comment by nulltoken** [comment]
>Done, amended to the old commit.

@johlo :+1:

@P0lip Could you please take a look?

**Pull request merged**
