### PR TITLE
Adds OS check to import of os-dependent binary in test-harness

### PR DESCRIPTION
**Pull request by AndrewBell**
**Checklist**

- [N/A] Tests added / updated
- [N/A] Docs added / updated

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

**Additional context**

Testing some new scenarios locally, I ran across this bug where the linux binary is hard coded in the test-harness. This adds an OS check via `process.os()` [docs](https://nodejs.org/api/os.html#os_os_platform), which should resolve as "darwin" on OSX, and fallback to linux otherwise.

I didn't see a Windows binary being created, so I believe this should cover both scenarios. Linting passed, but unsure of if/how to test. Please let me know if there is anything else I can do to help here, and thank you for taking a look!

### CODE REVIEW

**Comment by AndrewBell** [comment]
I'm not sure the CI failures are related to my changes, but let me know if that's not the case.

**Comment by P0lip** [comment]
@AndrewBell 
> I'm not sure the CI failures are related to my changes, but let me know if that's not the case.

They are not - everything is okay on the CI side in terms of tests.
We actually have a slightly invalid setup - any PRs coming from engineers outside Stoplight organization fail on the very last step, that is `cc-after`.

**Comment by AndrewBell** [comment]
Thanks for the info on the CI. Here's the error I get trying to run the linux binary: `/bin/sh: /Users/user/workspace/spectral/binaries/spectral-linux: cannot execute binary file`, but wasn't sure how to investigate from there.

**Comment by AndrewBell** [comment]
Let me take a crack at this later today. I'll let you know if I get stuck.

**Comment by AndrewBell** [comment]
That definitely looks better, provided no one wants to build a binary for a system they're not currently using. I see that `.circleci/config.yml` calls this as well, but I assume it should be fine.

`pkg`, when not supplied a `--targets` parameter, [defaults to the hosts' OS.](https://www.npmjs.com/package/pkg#targets). For example, here's a snippet from my local build logs from `yarn build.binary` 

```
$ pkg . --output ./binaries/spectral
> pkg@4.4.0
> Targets not specified. Assuming:
  node10-macos-x64
✨  Done in 28.33s.
```

Thanks for the nudge in the right direction, and let me know if there's anything else I can improve.

**Pull request merged**
