### PR TITLE
docs(asyncapi): Update asyncapi rules with updated AsyncAPI v2 URL.

### PR DESCRIPTION
**Pull request by RafaelJCamara**
**Checklist**

- [ ] Tests added / updated
- [X] Docs added / updated

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

**Screenshots**

**Before**:
image

**After**:
image

**Additional context**

When you go to the AsyncAPI rules, there's a link for the supported AsyncAPI specification version:
image

When you click the existing link, we get the 404 mentioned in the above screenshot.

With this PR, we get a new non-broken link.

### CODE REVIEW

**Review by mnaumanali94 — APPROVED** [review]

**Comment by mnaumanali94** [comment]
@RafaelJCamara Can you please update the commit message with the following conventions: https://github.com/semantic-release/semantic-release

**Comment by RafaelJCamara** [comment]
@mnaumanali94 please check

**Comment by RafaelJCamara** [comment]
Did my best to rename the commit, but the old one seems to be wondering around...

**Comment by RafaelJCamara** [comment]
I'll close this PR and create a new one clean.
new PR: https://github.com/stoplightio/spectral/pull/2618

**Pull request closed without merging**
