### PR TITLE
feat(core): improve ruleset validation

### LINKED ISSUE #2186: Invalid ruleset gives Error [object Object]
**Describe the bug**

An indentation error in a custom ruleset lead to a confusing error from spectral, leaving the user in an unclear state.

Spectral v6.4.1:

``` shell 
$ spectral lint example.yaml -r apisyouwonthate.yml
Error running Spectral!
Use --verbose flag to print the error stack.
Error #1: [object Object]

$ spectral lint example.yaml -r apisyouwonthate.yml --verbose
Error running Spectral!
Error #1: [object Object]
```

Spectral 6.2.0:

```
$ spectral lint example.yaml -r apisyouwonthate.yml
Error at #/: must NOT have additional properties
```

**To Reproduce**

1. Given any OpenAPI document and this ruleset `.spectral.yml`:

```yaml
rules:
  api-home:
    description: APIs MUST have a root path defined (`/`), to stop forcing all API consumers to visit documentation for basic interactions.
    severity: error
    given: $.paths
    then:
      field: /
      function: truthy

no-global-versioning:
  message: Server URL should not contain global versions
  given: $.servers[*].url
  then:
    function: pattern
    functionOptions:
      notMatch: /v[1-9]
  formats: oas3
  severity: warn
```

2. Run this CLI command `spectral lint https://raw.githubusercontent.com/stoplightio/Public-APIs/master/reference/plaid/openapi.yaml`
3. See error

**Expected behavior**
An error that explains my ruleset is invalid, ideally pointing to what I did wrong and where. 

```
Error #1: Ruleset contained an unexpected key `no-global-versioning:`
```

or 

```
Error #1: Ruleset should only contain `extends`, `formats`, or `rules` at the top level. 
```

Something like that. 

**Environment (remove any that are not applicable):**
 - Library version: Spectral CLI v6.4.1
 - OS: macOS

### PR DESCRIPTION
**Pull request by P0lip**
Fixes https://github.com/stoplightio/spectral/issues/2186

This will let us remove https://github.com/stoplightio/platform-internal/tree/f7fddbb1bfe6a760819a2568a7eed50732774af7/services/projects/src/utils/assertValidRuleset

A non-exhaustive list of changes:
- ~Added JSON Schema definitions that are suitable for JSON/YAML rulesets - going to be useful internally, particularly in the case of the ruleset-migrator package. Due to that, `assertValidRuleset` accepts a second parameter, namely `format`.~
- Fixed the validation of function options.
- Instead of a single error with all messages concatenated, we now throw an AggregateError to retain each validation error, and ultimately make the errors easier to consume. This resulted in a lot of test changes, as well as the addition of that custom expect matcher.
- ~Moved JSON Schema definitions describing rulesets from `src/meta` to `src/ruleset/meta`~
- ~Setup package exports so it's easier to import the validator~
- ~`FormatsSet` has been renamed to `Formats`~
- ~Improve `toJSON` signatures -> https://github.com/stoplightio/spectral/pull/2026/commits/2358b85666c222fcce3a657309ced44d4a69aad8~
- ~Moved some files under `src/ruleset` around to unify the directory structure~

Do note that although some changes are marked as additions, they are not such - it's mostly me slicing certain chunks of code into separate files. In other words, a notable deletion of code is usually followed by an addition somewhere.

**Checklist**

- [x] Tests added / updated
- [ ] Docs added / updated

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by Nezteb** [comment]
@P0lip @mmiask This PR is pretty stale. Can it be closed? If not, what is its priority?

**Comment by mmiask** [comment]
> @P0lip @mmiask This PR is pretty stale. Can it be closed? If not, what is its priority?

@Nezteb IMHO this should be review ASAP, although I've been busy with sprint-related stuff. I'll take a look as soon as I can.

**Comment by P0lip** [comment]
Let's review https://github.com/stoplightio/spectral/pull/2062 first. It's a subset of the following PR.

**Comment by pamgoodrich** [comment]
@P0lip : Does this issue require Spectral doc updates and if so, would you like help?

**Comment by P0lip** [comment]
Thanks @pamgoodrich, I think we're good. This mostly improves the existing functionality, so I expect no docs changes to be required, but I'll make sure to let you know in case something changes.

**Review by philsturgeon — DISMISSED** [review]
We know im not the best at the sort of super advanced TypeScript here, but I believe the tests speak for themselves, and I can trust @P0lip with the rest.

**Review by mnaumanali94 — DISMISSED** [review]

**Pull request merged**
