### PR TITLE
fix(functions): schema enum option

### PR DESCRIPTION
**Pull request by mallachari**
Required by https://github.com/stoplightio/platform-internal/issues/9295

Adds type property to dialect enum option for schema function

**Checklist**

- [ ] Tests added / updated
- [ ] Docs added / updated

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by P0lip — CHANGES_REQUESTED** [review]
This should be fixed elsewhere.
Enum usually isn't used with type keyword, so fixing the piece of code here won't fix other potential usages of enum.

**Comment by mallachari** [comment]
There is only one other usage of enum within that file for casing function and it has type property set to string. Couldn't all properties for function options have type assigned?

**Comment by P0lip** [comment]
> There is only one other usage of enum within that file for casing function and it has type property set to string. Couldn't all properties for function options have type assigned?

but these options can be specified by users as well, they are not specific to `spectral-functions` packages.
Each custom function may specify its own too.

I'm just not sure why using `type` helps tho.

Using type with enum is kind of like you did the following in TS

```ts
type Abc = string & ('foo' | 'bar');
```
where `string` is the `type: string`, and `'foo' | 'bar'` is `enum: [foo, bar]`

We should just render a dropdown anytime there's an enum.

**Comment by mallachari** [comment]
Alright, alright, I feel convinced :D

**Pull request closed without merging**
