### PR TITLE
fix: address Webpack warning

### LINKED ISSUE #1431: Warnings critical dependency with webpack
**Describe the bug**
Not sure if it could be classified as bug, but during the build phase, webpack throws out some warnings like these
```bash
WARNING in ./node_modules/@stoplight/spectral/dist/rulesets/evaluators.js 57:15-22
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ./node_modules/@stoplight/spectral/dist/spectral.js 18:21-53
 @ ./node_modules/@stoplight/spectral/dist/index.js 5:21-42
 @ ./index.js 1:0-60 2:19-27 3:32-43

WARNING in ./node_modules/@stoplight/spectral/dist/rulesets/finder.js 16:15-35
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@stoplight/spectral/dist/rulesets/reader.js 8:17-36
 @ ./node_modules/@stoplight/spectral/dist/rulesets/index.js 5:15-34
 @ ./node_modules/@stoplight/spectral/dist/spectral.js 17:19-40
 @ ./node_modules/@stoplight/spectral/dist/index.js 5:21-42
 @ ./index.js 1:0-60 2:19-27 3:32-43

```

**To Reproduce**
```bash
git clone https://github.com/emilioSp/spectral-webpack.git
yarn
yarn build
```

then you should see 6 warnings in the console.

**Expected behavior**
No warnings.

**Environment (remove any that are not applicable):**
 - Library version: 5.7.2
 - OS: MacOS Big Sur

### PR DESCRIPTION
**Pull request by P0lip**
Fixes https://github.com/stoplightio/spectral/issues/1431

**Checklist**

- [x] Tests added / updated
- [x] Docs added / updated

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

### CODE REVIEW

**Comment by wmhilton** [comment]
This raises so many eyebrows, I've run out of eyebrows to raise.

**Comment by philsturgeon** [comment]
But why? :D

**Comment by wmhilton** [comment]
Can I suggest doing it [properly](https://github.com/webpack/webpack/issues/8826#issuecomment-660594260)?

**Review by billiegoose — APPROVED** [review]
eh screw it. nobody uses CSP amirite?

**Comment by P0lip** [comment]
> eh screw it. nobody uses CSP amirite?

Yeah. Honestly, I'm planning to go away from `require` calls and organize the project a bit better to leverage conditional exports.
I'm not delighted with the current state of things related to browser vs Node.js lands support.

**Pull request merged**
