### PR TITLE
Release v4.0.1

### PR DESCRIPTION
**Pull request by philsturgeon**
Two reviews required as this is going to master.

### CODE REVIEW

**Comment by XVincentX** [comment]
@P0lip This bump was required because, since we're installing the dep from Git directly the build script isn't run, right?

**Comment by philsturgeon** [comment]
@XVincentX that's right. Check the CHANGELOG I just pushed, it'll explain it.

**Comment by XVincentX** [comment]
We could really use the GitHub registry package to quickly publish our forks :(

**Comment by philsturgeon** [comment]
Make github issues for any cool ideas you have and/or start a slack thread :D

**Comment by P0lip** [comment]
> @P0lip This bump was required because, since we're installing the dep from Git directly the build script isn't run, right?

No, it's the other way around actually. We do not want to run the build script, since it's supposed to fail on Windows. Moreover, we ship bundled code, so there is no valid reason to run the script given the built files are already accessible.

**Pull request merged**
