### PR TITLE
feat: new shape of validation results [SL-2123]

### PR DESCRIPTION
**Pull request by P0lip**
TODO:

- [x] Switch to npm version of `@stoplight/types` once released
- [x] Make IDiagnostic['range'] optional? `parseWithPointers` function exposed by [JSON](https://github.com/stoplightio/json/pull/12)/[YAML](https://github.com/stoplightio/yaml/pull/6)/[Markdown](https://github.com/stoplightio/markdown/pull/5) parsers will be capable of providing the required information, but Spectral would need to make use of it for text files (when CLI mode is added to Spectral). Not sure about object literals (current usage via API), as they aren't expressed in text format.
I guess we could simply treat each property as it would be placed on a separate line and indentation could be based on actual nesting depth (BASE * depth).

### Please check if the PR fulfills these requirements
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce?

Feature (breaking). 

### If this is a feature change, what is the new behavior?

The shape of a single validation object is different.

### Does this PR introduce a breaking change?

Yes, as stated above, the shape of single validation is different, so expect some properties to be missing, new ones to be added or their values to be changed.

#### What changes might users need to make in their application due to this PR?

Use new properties.

### CODE REVIEW

**Comment by marbemac** [comment]
👍 a couple of thoughts:

- will need some way to get `summary` for given `code` (should be easy lookup on rule)
- can we figure out a way to not include `range` at all for right now (without changing @stoplight/types)? can add range later once we have a proper solution

**Comment by P0lip** [comment]
> can we figure out a way to not include range at all for right now (without changing @stoplight/types)? can add range later once we have a proper solution

I believe the easiest way would be the following
```diff
-export interface IRuleResult extends IDiagnostic {
+export interface IRuleResult extends Omit<IDiagnostic, 'range'> {
  path: JSONPath;
}
```

**Comment by P0lip** [comment]
> will need some way to get summary for given code (should be easy lookup on rule)

Doesn't `message field serve that purpose?

**Comment by marbemac** [comment]
> Doesn't `message field serve that purpose?

Message is the actual error message, summary is the rule summary. We use summary in the UI so that end user understands what the rule is trying to do.

**Comment by P0lip** [comment]
> Message is the actual error message, summary is the rule summary. We use summary in the UI so that end user understands what the rule is trying to do.

Shall we keep it exclusive to `IRuleResult`? Don't really see how they would be useful for json/yaml parsing errors.

**Comment by philsturgeon** [comment]
Can you change the base branch for this PR to release/2.0 please?

**Comment by marbemac** [comment]
> Shall we keep it exclusive to IRuleResult? Don't really see how they would be useful for json/yaml parsing errors

Yeah `summary` should remain specific to Spectral so can just add back here.

Otherwise looks good!

**Pull request merged**
