### PR TITLE
fix(deps): bump yargs from 15.4.1 to 16.2.0

### PR DESCRIPTION
**Pull request by dshiledarc1**
Fixes #1529 

**Checklist**

- [x] Tests added / updated
- [x] Docs added / updated

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by P0lip — COMMENTED** [review]
You need to run yarn to update lockfile (`yarn.lock`).

**Comment by dshiledarc1** [comment]
@P0lip Hi added yarn.lock to the PR. 

ran yarn test 
Test Suites: 72 failed, 68 passed, 140 total
Tests:       9 failed, 1004 passed, 1013 total
Snapshots:   1 passed, 1 total
Time:        17.013s, estimated 22s

Let me know if anything else is needed.

**Comment by dshiledarc1** [comment]
@P0lip Genetle Reminder to review PR.

**Comment by P0lip** [comment]
Hey, there's a test-harness scenario that needs to be updated.
Could you please update it so that CI checks are green?
Thank you!

**Comment by dshiledarc1** [comment]
@P0lip I am getting test failures - with node --version
v10.18.1

Test Suites: 72 failed, 68 passed, 140 total
Tests:       9 failed, 1004 passed, 1013 total
Snapshots:   1 passed, 1 total
Time:        26.493s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
On the main repo develop branch - 
Your branch is up to date with 'origin/develop'.
git remote -v
origin	https://github.com/stoplightio/spectral.git (fetch)
origin	https://github.com/stoplightio/spectral.git (push)

This is event before making any changes. Do you think there is an issue in the develop.

**Comment by P0lip** [comment]
Try running `yarn test.prod` and see what it yields.
`develop` is certainly okay, because CI checks are green in other PR, and I haven't observed any glitches in my local env either.
It might have something to do with the excessive `yarn.lock` file. Did you regenerate it?
If so, you should revert the change.
```
git checkout origin/develop -- yarn.lock
yarn
```

**Comment by dshiledarc1** [comment]
@P0lip With node version 12.0 - Since I am on the base repo, there is no change to yarn.lock. I get -

yarn build

 $ copyfiles -u 1 "dist/rulesets/{oas,asyncapi}/functions/*.js" ./
$ ts-node --compiler-options {\"module\":\"CommonJS\"} ./scripts/generate-assets.ts
(node:26502) UnhandledPromiseRejectionWarning: ResolverError: Error downloading http://json-schema.org/draft-04/schema
socket hang up
    at /Users/egt447/exchange/schema-work/src/spectral/node_modules/@apidevtools/json-schema-ref-parser/lib/resolvers/http.js:127:16
(node:26502) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:26502) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

yarn test , shows the same failures - 
Test Suites: 72 failed, 68 passed, 140 total
Tests:       9 failed, 1004 passed, 1013 total
Snapshots:   1 passed, 1 total
Time:        19.933s, estimated 26s


And yarn test.prod end with error - 
src/rulesets/asyncapi/__tests__/__helpers__/createWithRules.ts:9:47 - error TS2307: Cannot find module '../../../../../rulesets/assets/assets.asyncapi.json' or its corresponding type declarations.

9     Object.assign(STATIC_ASSETS, await import('../../../../../rulesets/assets/assets.asyncapi.json'), {
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

src/rulesets/oas/__tests__/__helpers__/createWithRules.ts:12:47 - error TS2307: Cannot find module '../../../../../rulesets/assets/assets.oas.json' or its corresponding type declarations.

12     Object.assign(STATIC_ASSETS, await import('../../../../../rulesets/assets/assets.oas.json'), {
                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors.

error Command failed with exit code 1.

Is there a way we can collaborate over a zoom call, I can send you an invite, please suggest a time, I am in PST timezone. I am new to Spectral Community, and will be happy to contribute.

**Comment by P0lip** [comment]
> (node:26502) UnhandledPromiseRejectionWarning: ResolverError: Error downloading http://json-schema.org/draft-04/schema
socket hang up

This is the cause of the failure.
What does `curl http://json-schema.org/draft-04/schema` yield?

**Comment by dshiledarc1** [comment]
Hi @P0lip on the command line - 
curl http://json-schema.org/draft-04/schema --- returns the full schema.
{
    "id": "http://json-schema.org/draft-04/schema#",
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "Core schema meta-schema",
    "definitions": {
        "schemaArray": {


But I still get the error in yarn build - I am on mac os - $ copyfiles -u 1 "dist/rulesets/{oas,asyncapi}/functions/*.js" ./
$ ts-node --compiler-options {\"module\":\"CommonJS\"} ./scripts/generate-assets.ts
(node:16008) UnhandledPromiseRejectionWarning: ResolverError: Error downloading http://json-schema.org/draft-04/schema
socket hang up

**Comment by dshiledarc1** [comment]
@P0lip Gentle reminder to help me resolve the issue.

**Comment by P0lip** [comment]
Hey, I'm afraid there's not much I can do about it. :disappointed:
We've never had anyone run into this particular issue - it worked just fine for everyone, thus it's difficult for me to say what could be causing the issue.
We also perform that step during our CI builds and they never failed with the error like yours.
Are you behind some proxy? Also did you try googling for `socket hang up`?

I can take over this PR and get it over the finish line if you want.

**Comment by dshiledarc1** [comment]
Hi @P0lip Really appreciate your offer to take over the PR, as you are spending more time resolving my local environment issues. 

Please do the needful with the PR, and hopefully in future I can contribute in other areas of the project. 

Thanks
Devendra

**Comment by dshiledarc1** [comment]
@P0lip  Please let me know if I can be of any help, to get this PR to finish line. Thanks, Devendra

**Comment by P0lip** [comment]
> Please do the needful with the PR, and hopefully in future I can contribute in other areas of the project.

In future, we might potentially get rid of that `json-schema.org` request in the build pipeline, but for the time being it's essential :disappointed:

**Comment by P0lip** [comment]
Hey!
The PR is here https://github.com/stoplightio/spectral/pull/1551

**Review by domagojk — DISMISSED** [review]

**Comment by P0lip** [comment]
The PR is in. I'll close this one.
Thanks a bunch for your effort!

**Comment by dshiledarc1** [comment]
@P0lip Thank you very much for the prompt action.

**Pull request closed without merging**
