### PR TITLE
Add logo

### PR DESCRIPTION
**Pull request by tbarn**
### What kind of change does this PR introduce?

Add Spectral logo

### CODE REVIEW

**Comment by lottamus** [comment]
image

I think itll look something like this

**Comment by tbarn** [comment]
https://github.com/stoplightio/spectral/tree/logo

**Comment by lottamus** [comment]
Looks good! What do you think about cropping the image a little bit on the left so the left most dot in the logo is aligned with the headers and test coverage banner?

**Comment by tbarn** [comment]
tagging @rowa97 so he can see this. he was doing the logo editing.

**Comment by tbarn** [comment]
Fixed it up.

**Pull request merged**
