### PR TITLE
feat(ruleset): optional pointer for exceptions

### PR DESCRIPTION
**Pull request by P0lip**
Makes pointers optional as described in https://github.com/stoplightio/spectral/issues/1002
Addresses https://github.com/stoplightio/platform-internal/issues/4523

**Checklist**

- [x] Tests added / updated
- [x] Docs added / updated

**Does this PR introduce a breaking change?**

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by billiegoose — APPROVED** [review]
Love it. Sweet and simple.

**Comment by jcolaco-nmz** [comment]
@P0lip Do you have any estimation on when will this be released?

**Comment by P0lip** [comment]
Hey @jcolaco-nmz, no specific timeline yet, but I'm hoping to get it out before 2020 ends.

**Comment by P0lip** [comment]
@jcolaco-nmz Hey, just wanted to let you know the change has been released.

**Pull request merged**
