### PR TITLE
feat(rulesets): add AsyncAPI v3 support

### LINKED ISSUE #2559: Support for AsyncAPI v3.0.0
**User story.**
As an API designer, I can use Spectral linter, so that I can lint my version 3.0.0 specifications.

**Is your feature request related to a problem?**
Version 3.0.0 is not supported by Spectral

**Describe the solution you'd like**
Extend the ruleset to support v3.0.0

**Additional context**
https://www.asyncapi.com/blog/release-notes-3.0.0

### PR DESCRIPTION
**Pull request by jonaslagoni**
Fixes https://github.com/stoplightio/spectral/issues/2559.

**Checklist**

- [X] Tests added / updated
- [X] Docs added / updated

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

**Additional context**

Does not update the following rules:
- asyncapi-message-examples
- asyncapi-message-messageId-uniqueness
- asyncapi-operation-operationId-uniqueness
- asyncapi-operation-security
- asyncapi-schema-default (does technically not work correctly, as it does not check default across all schemas i.e. message payloads)
- asyncapi-schema-examples (does technically not work correctly, as it does not check default across all schemas i.e. message payloads)
- asyncapi-payload (require custom function to tune out multi-format schema objects as schemaFormat is no longer part of message)
- asyncapi-payload-default (require custom function to tune out multi-format schema objects as schemaFormat is no longer part of message)
- asyncapi-payload-examples(require custom function to tune out multi-format schema objects as schemaFormat is no longer part of message)
- asyncapi-operation-operationId (No longer relevant)

Limits to rules:
- asyncapi-3-payload-unsupported-schemaFormat - Does not apply for multi-format schemas

### CODE REVIEW

**Comment by jonaslagoni** [comment]
The last CircleCI test are simply timing out, no idea how to fix that.

All ready to be reviewed.

**Review by frankkilcommins — COMMENTED** [review]
Looking good so far. Some minor remarks:

- Formats Package:
  - Bump package version to `1.8.0`
  - Update deps in consuming packages: functions, ruleset-bundler, rulesets, and core (devDependencies)
- Rulesets Package:
  - Bump package version to `1.21.0`

**Comment by jonaslagoni** [comment]
@frankkilcommins are those not automatically bumped on release? 🤔

**Comment by jonaslagoni** [comment]
Alright, updated dependencies, but I am getting some weird dependency problems in code I have not touched...

Any suggestions?

**Comment by frankkilcommins** [comment]
> @frankkilcommins are those not automatically bumped on release? 🤔

Oh maybe - I've not seen the release job but I manually bumped when adding Arazzo core rulesets. @mnaumanali94 can you confirm.

**Comment by mnaumanali94** [comment]
@frankkilcommins semantic-release does bump it automatically if the commit messages are done right.

**Comment by jonaslagoni** [comment]
So I guess I revert the manual version bumping? 🤔 

Anything else that needs to happen?

**Comment by mnaumanali94** [comment]
@jonaslagoni I have fixed the CI - There are some conflicts in docs, so if you can fix those and merge the develop branch, the checks should pass.

> So I guess I revert the manual version bumping? 🤔

Yes that should be it.

**Comment by jonaslagoni** [comment]
> @jonaslagoni I have fixed the CI - There are some conflicts in docs, so if you can fix those and merge the develop branch, the checks should pass.
> 
> > So I guess I revert the manual version bumping? 🤔
> 
> Yes that should be it.

All good, looking at it tomorrow most likely :v:

**Comment by jonaslagoni** [comment]
All ready :v: @mnaumanali94 @frankkilcommins

**Review by frankkilcommins — APPROVED** [review]

**Comment by msolujic** [comment]
thanks @frankkilcommins 
which version of spectral this will be part of?

**Comment by frankkilcommins** [comment]
@msolujic we hope to include in the next release. We should get that out the door over the next week or so.

cc @mnaumanali94

**Comment by dilanka-cacib** [comment]
Hi,

Do you have ETA to release this feature? 
I can see you have updated your [doc](https://docs.stoplight.io/docs/spectral/1e63ffd0220f3-async-api-rules#asyncapi-v3) with new v3 rules but I cannot see those rules in [@stoplight/spectral-rulesets](https://www.npmjs.com/package/@stoplight/spectral-rulesets?activeTab=versions)

Thanks,

**Comment by msolujic** [comment]
the last release was in september https://github.com/stoplightio/spectral/releases/tag/v6.13.1 
please let us know here when this thing goes to official release @frankkilcommins 
thanks

**Pull request merged**
