### PR TITLE
DO NOT MERGE AS-IS - WIP! feat: CLI

### PR DESCRIPTION
**Pull request by MikeRalphson**
**DO NOT MERGE - WORK IN PROGRESS!**

I wanted to stop around this point, where the CLI is usable but before any polishing has been done, to see whether I'm on the right track.

### Please check if the PR fulfills these requirements
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

### What kind of change does this PR introduce?

Feature

### What is the current behavior?

Spectral has no CLI.

### If this is a feature change, what is the new behavior?

CLI is provided.

### Does this PR introduce a breaking change?

No.

What changes might users need to make in their application due to this PR?

None.

### Other information

A CLI is provided based on `oclif` as suggested. It is excluded from the built module by use of the `package.json` `files` directive, as requested (tested with `npm pack`).

It provides linting of Swagger/OpenAPI 2.0 and OpenAPI 3.x documents, either from a local file or URL, with optional resolution of external `$ref`s.

It returns an exit code for 0 for success, 1 for warnings and 2 for errors, so should be suitable for use in CI environments (instructions on installing by cloning from the repository and performing `yarn install`s would need to be added).

A basic `README.md` has been added.

* [ ] As yet there is no support for loading custom functions or rules, or support for non-OpenAPI documents. Guidance on the best way to approach this would be appreciated.

### CODE REVIEW

**Comment by marbemac** [comment]
Ok finally had a chance to check this out in depth, great work! I went ahead and cleaned up some things, we're pretty close now. I meant to push it to a new branch but accidentally pushed to your cli branch, I hope that's ok - if not lmk and we can move the commit to another branch!

Changes I made:

- flattened the CLI into main package. 
  - after a bit of thought I think its more trouble than it is worth to maintain another package inside the package (cc @chris-miaskowski). since we don't bundle published package into a single file, there is no extra code added to users using spectral as a library
- updated build process to prepare the cli correctly. after running `yarn build` in root, you can now `cd dist` and `./bin/run`!
- formatted code, and added spacing to improve legebility
- removed redundant top level promise from lint function
- consistently throw errors in lint function instead of sometimes using oclif.error
- fixed all ts and tslint errors
- removed resolve flag for now, I think we'll want to think through this one a little more and can do it after first cli release (see future work below)

Still todo before PR is ready:

- when printing results, distinguish between the validation levels. the level is present on the result object in the `severity` property. suggest importing and checking against this enum: https://github.com/stoplightio/types/blob/next/src/validations.ts#L3-L7
- maxWarn -> maxResults (since results are not all warnings - can be info, warn, or error)
- what's the best way to output/format the results when printing them out to screen? we should see what the convention is in other popular linters
- tests: testing the cli is not as easy as regular tests. we have some examples here: https://github.com/stoplightio/scripts/tree/master/src/commands/__tests__

Out of scope potential future work after this first CLI release:

- resolving, and reporting resolve errors like invalid $ref, etc. suggest our https://github.com/stoplightio/json-ref-resolver for this. it is VERY battle tested
- flag to log results to file in xyz standard format for further processing
- flag to load custom ruleset file
- flag to load custom functions

**Comment by tbarn** [comment]
@MikeRalphson just got to try it out and it looks awesome. We are getting super close to announcing Spectral. I know we took a bit to get back to you on this PR, but I'm curious what your availability is over the next week or two. We'd love to get this in there before it is announced.

**Comment by MikeRalphson** [comment]
Should have time this coming week to action the first set of points above.

**Comment by MikeRalphson** [comment]
#### Phase 2 checklist

* [ ]  when printing results, distinguish between the validation levels. the level is present on the result object in the `severity` property. suggest importing and checking against this enum: https://github.com/stoplightio/types/blob/next/src/validations.ts#L3-L7
* [x] maxWarn -> maxResults (since results are not all warnings - can be info, warn, or error)
* [ ] what's the best way to output/format the results when printing them out to screen? we should see what the convention is in other popular linters. **Will look at Speccy, EsLint, TsLint etc**
* [ ] tests: testing the cli is not as easy as regular tests. we have some examples here: https://github.com/stoplightio/scripts/tree/master/src/commands/__tests__

**Comment by MikeRalphson** [comment]
@marbemac re:

>  tests: testing the cli is not as easy as regular tests

the link appears broken and tests removed in the latest commit. Does https://github.com/stoplightio/scripts/tree/4706e887eb1fef308984ace407e0a2b9f263def9/src/commands/%5F%5Ftests%5F%5F still contain good examples?

**Comment by marbemac** [comment]
> still contain good examples?

Yup! We just removed those two commands in a recent release of that repo. But the tests that you linked to are still a decent example. Don't take that as gospel though, there very well may be a better way to test this stuff, just figured I share some prior art to get ya started.

**Comment by tbarn** [comment]
Hey @MikeRalphson, just a heads up. It sounds like this week we are finally ready to announce Spectral in a blog post. I was going to mention that this CLI PR is almost across the finish line, is that alright with you?

**Comment by MikeRalphson** [comment]
@tbarn yep - I've found some resources on testing oclif CLIs and have made a bit of progress on the output formatting, so I think we're nearly there.

**Comment by philsturgeon** [comment]
@MikeRalphson hey, there is a bit of a change coming up to make run be async, but that shouldn't be too awful for you. #99

**Comment by philsturgeon** [comment]
Can you change the base branch for this PR to release/2.0 please?

**Comment by philsturgeon** [comment]
I have incorporated all of this work into #105 and got it up to date with some recent changes. I suggest we work on it over, and if anyone has advice or tips they can PR off my PR perhaps!

**Pull request closed without merging**
