### PR TITLE
feat(rulesets): add unused components server rule

### PR DESCRIPTION
**Pull request by jonaslagoni**
Partly solves https://github.com/stoplightio/spectral/issues/1103

**Checklist**

- [X] Tests added / updated
- [X] Docs added / updated

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

### CODE REVIEW

**Comment by P0lip** [comment]
@jonaslagoni assuming you've received an invite and accepted it (which seems like you do according to what GH settings page tells me), perhaps create a branch in the Spectral repo itself?
You're welcome to create branches directly in the repo.
This should help with CI checks and our CircleCI setup doesn't like forks particularly much.

**Comment by jonaslagoni** [comment]
> You're welcome to create branches directly in the repo.
> This should help with CI checks and our CircleCI setup doesn't like forks particularly much.

Haha, alright, I'll try to remember. It's just the standard we apply under AsyncAPI and the one that creates less clutter in upstream 😄 

I was wondering why the jobs was not picked up by the CI 😅

**Comment by P0lip** [comment]
> Haha, alright, I'll try to remember. It's just the standard we apply under AsyncAPI and the one that creates less clutter in upstream 😄

Well, you can use the fork if that's how you approach it. I just wanted to let you know you can create branches here too, but it's not compulsory by any means, so you can continue to use the fork if that's how you do things.

> I was wondering why the jobs was not picked up by the CI 😅

It should work just fine and it usually does, but for some reason, it got stuck this time around.
If that continues to happen, I'll spend some time investigating that.
I know we had a similar issue in https://github.com/stoplightio/prism for certain contributors, so it's not an isolated case.

**Review by P0lip — APPROVED** [review]
It seems like I'll need to merge this one cause of the CI.
LMK when you're good with the change, and I'll do it.
it's 👌 from my side

**Comment by jonaslagoni** [comment]
> It seems like I'll need to merge this one cause of the CI.
> LMK when you're good with the change, and I'll do it.
> it's 👌 from my side

Fine by me yea 👍

**Comment by jonaslagoni** [comment]
I think we should block this until https://github.com/stoplightio/spectral/issues/1103#issuecomment-1071788756 is resolved, otherwise it would be a breaking-change to change it 🙂

**Pull request merged**
