### PR TITLE
feat(rulesets): support AsyncAPI 2.4

### LINKED ISSUE #2145: Add support for AsyncAPI 2.4
**User story.**
As a user, I want to be able to use the newest AsyncAPI version in spectral.

### PR DESCRIPTION
**Pull request by jonaslagoni**
Fixes #2145

**Checklist**

- [X] Tests added / updated
- [X] Docs added / updated

**Does this PR introduce a breaking change?**

- [ ] Yes
- [X] No

### CODE REVIEW

**Review by P0lip — APPROVED** [review]

**Comment by P0lip** [comment]
Ah, it's the CI check again.
There's something off with the fork

**Comment by jonaslagoni** [comment]
> Ah, it's the CI check again.
> There's something off with the fork

Anything you know I need to change? Or should I just start using the branches in `stoplightio/spectral` instead 😆

**Comment by P0lip** [comment]
> ing you know I need to change? Or should I just start using the branches in stoplightio/spectral instead 😆

No clue, I'd probably need to reach out to CircleCI. That issue isn't specific to Spectral, it happens to some forks of stoplightio/prism as well.
Nonetheless, you can indeed push straight onto stoplightio/spectral :)

**Comment by jonaslagoni** [comment]
> No clue, I'd probably need to reach out to CircleCI. That issue isn't specific to Spectral, it happens to some forks of stoplightio/prism as well.
> Nonetheless, you can indeed push straight onto stoplightio/spectral :)

Alright, I am gonna do that going forward then 🙂 Thanks!

**Pull request merged**
