### PR TITLE
chore: bump http-spec and types versions

### PR DESCRIPTION
**Pull request by lag-of-death**
## Changes

This PR updates its dependencies to work with adjusted `IHttpOperation` type from `@stoplight/types` (https://github.com/stoplightio/types/pull/50) because of https://github.com/stoplightio/prism/pull/514.

(Temporarily includes `dist` folder.)

## Dependencies

https://github.com/stoplightio/spectral/blob/ca10406c8798cb7b19f1e9de8c809b6b19e695b9/package.json#L65

https://github.com/stoplightio/spectral/blob/ca10406c8798cb7b19f1e9de8c809b6b19e695b9/package.json#L67

Temporarily depends on `dist` from `@stoplight/json-ref-resolver`:
https://github.com/stoplightio/spectral/blob/ca10406c8798cb7b19f1e9de8c809b6b19e695b9/src/resolvers/http.ts#L1

The dependency on `dist` from `@stoplight/types` was already there (although in most of the places the dependency is just on `types`).

## Plan:
- wait for the dependencies to be merged 
- update `package.json` to point to built versions of `json-ref-resolver` and `types`
- have an approval
- remove `dist` folder 
- merge

**Why github branches and no `yalc`? I was trying `yalc` first, but were having issues with nested `.yalc` folders (like `.yalc/@stoplight/something/.yalc/@stoplight/something_else`). Yarn, for some reason, couldn't have resolved dependencies.**

## Order of merging:
1. `@stoplight/types` (https://github.com/stoplightio/types/pull/50)
2. `@stoplight/json-ref-resolver` (https://github.com/stoplightio/json-ref-resolver/pull/86)
3. `@stoplight/http-spec` (https://github.com/stoplightio/http-spec/pull/15) and `@stoplight/spectral` (https://github.com/stoplightio/spectral/pull/444)
4. `@stoplight/graphite` (https://github.com/stoplightio/graphite/pull/211) and `@stoplight/prism` (https://github.com/stoplightio/prism/pull/514)

### CODE REVIEW

**Comment by lag-of-death** [comment]
@P0lip, `dist` folder was needed for creating a PR for `graphite` https://github.com/stoplightio/graphite/pull/211 (where there were a couple of `/dist`, like this:
https://github.com/stoplightio/graphite/blob/f90c608e98a51ec24f19e0d809dc28a52ae360fa/src/plugins/spectral/diagnoseSourceNode.ts#L3
when importing `types` module, and this branch didn't have it, since of course, it was not built). 

This is ready to be reviewed, but if you might, please take a look at https://github.com/stoplightio/types/pull/50, which is the tip of this iceberg

**Comment by P0lip** [comment]
@lag-of-death we don't need dist to be committed though.

**Comment by lag-of-death** [comment]
@P0lip, it will be removed, please take a look at *Plan* section in the description (I just added it).

**Comment by P0lip** [comment]
@lag-of-death we shouldn't be committing that at all until the types pkg is bumped.

**Comment by lag-of-death** [comment]
@P0lip, next time, I won't push anything until a bump in types

**Comment by philsturgeon** [comment]
Hey sorry the develop rebase really did a number on this one, can you try and rebase develop?

**Comment by lag-of-death** [comment]
no need now, already resolved with @dependabot-bot

**Pull request closed without merging**
